const {chromium,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
const path=require('node:path');
const {start}=require('./review-server.cjs');
(async()=> {
  const server=start(43128),browser=await chromium.launch({headless:true});
  const out=path.resolve('output/playwright/admin-map'); await fs.mkdir(out,{recursive:true});
  const context=await browser.newContext({viewport:{width:1440,height:1100}});
  const page=await context.newPage(), errors=[], mutations=[], external=[], dialogs=[];
  const resources=[],geometry=[];
  page.on('response',response=> { if(response.url().includes('/assets/maps/spain-communities.svg')) resources.push({url:response.url(),status:response.status(),type:response.headers()['content-type']}); });
  page.on('dialog',async dialog=>{dialogs.push(dialog.message());await dialog.dismiss();});
  page.on('pageerror',e=>errors.push(e.message));
  await context.route('**/*',route=> {
    const req=route.request(),url=new URL(req.url());
    if (!['127.0.0.1','localhost'].includes(url.hostname)) { external.push(url.host); return route.abort(); }
    if(req.method()!=='GET') { mutations.push(req.url()); return route.abort(); }
    return route.continue();
  });
  async function recordGeometry(target,name) {
    await expect(target.locator('.map-graphic svg')).toBeVisible();
    const result=await target.locator('.map-graphic svg').evaluate(svg=>({width:svg.getBoundingClientRect().width,height:svg.getBoundingClientRect().height,
      visibleRegions:[...svg.querySelectorAll('[data-region]')].filter(g=>g.getBoundingClientRect().width>0&&g.getBoundingClientRect().height>0).length}));
    expect(result.width).toBeGreaterThan(200);expect(result.height).toBeGreaterThan(150);expect(result.visibleRegions).toBe(19);
    geometry.push({name,...result});
  }
  try {
    let releaseSales;
    const waitingSales=new Promise(resolve=>{releaseSales=resolve;});
    await page.route('**/api/admin/map?**',async route=>{await waitingSales;await route.continue();});
    await page.goto('http://127.0.0.1:43128/admin.html#section-map');
    await expect(page.locator('#section-map')).toBeVisible();
    await expect(page.locator('nav > .sidebar-destination[data-nav-target="section-map"]')).toBeVisible();
    await expect(page.locator('#navCliente [data-nav-target="section-map"]')).toHaveCount(0);
    await expect(page.locator('[data-nav-target="section-map"]')).not.toHaveAttribute('aria-controls',/.+/);
    await expect(page.locator('[aria-controls="navCliente"]')).toHaveAttribute('aria-expanded','false');
    await recordGeometry(page,'desktop-loading');
    await expect(page.locator('.map-status')).toHaveText('Cargando ventas…');
    await expect(page.locator('.map-legend')).toContainText('Cargando ventas');
    await page.screenshot({path:path.join(out,'desktop-loading.png')});
    releaseSales();
    await expect(page.locator('.map-graphic [data-region]')).toHaveCount(19);
    await expect(page.locator('.map-regions-table tbody tr')).toHaveCount(19);
    await expect(page.locator('[name="preset"]')).toHaveValue('month');
    await expect(page.locator('.map-cards').getByText('90',{exact:true})).toBeVisible();
    await page.unroute('**/api/admin/map?**');
    await expect(page.locator('.map-legend')).toContainText('0');
    const madrid=page.locator('.map-graphic [data-region="13"]');
    await madrid.hover(); await expect(page.locator('.map-tooltip')).toContainText('Comunidad de Madrid');
    await madrid.focus(); await expect(page.locator('.map-tooltip')).toContainText('Comunidad de Madrid');
    await page.keyboard.press('Enter');
    await expect(page.locator('.map-detail')).toBeVisible();
    await expect(page.locator('.map-detail [data-order]')).toHaveCount(25);
    await expect(madrid).toBeFocused();
    await page.locator('.map-detail [data-page="1"]').click();
    await expect(page.locator('.map-pagination')).toContainText('Página 2');
    await expect(page.locator('.map-detail [data-order]')).toHaveCount(12);
    await page.locator('.map-detail [data-order]').first().click();
    await expect(page.locator('#orderDetailModal')).toBeVisible();
    await page.locator('#orderDetailClose').click();
    await page.locator('[name="metric"]').selectOption('revenueCents');
    await expect(page.locator('.map-legend')).toContainText('€');
    await page.locator('[data-sort="name"]').click();
    await expect(page.locator('[data-column="name"]')).toHaveAttribute('aria-sort','descending');
    await page.getByRole('switch',{name:'Modo oscuro'}).click();
    await page.screenshot({path:path.join(out,'desktop.png'),fullPage:true});
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(out,'desktop-map.png')});
    await recordGeometry(page,'desktop-simulated');
    await page.screenshot({path:path.join(out,'desktop-simulated.png')});
    await page.locator('[name="preset"]').selectOption('today');
    await expect(page.locator('.map-pagination')).toContainText('Página 1');
    await page.locator('[name="preset"]').selectOption('year');
    await expect(page.locator('.map-status')).toBeEmpty();
    await page.locator('[name="preset"]').selectOption('all');
    await expect(page.locator('[name="from"]')).toHaveValue('2000-01-01');
    await expect(page.locator('.map-status')).toBeEmpty();
    await page.evaluate(()=>window.CRONOX_ADMIN_NAV.navigate('section-orders'));
    await expect(page.locator('#section-orders')).toBeVisible();
    await page.goBack();
    await expect(page.locator('#section-map')).toBeVisible();
    await expect(page.locator('.map-status')).toBeEmpty();
    await page.locator('[data-select="foreign"]').click();
    await expect(page.locator('.map-detail')).toContainText('Fuera de España');
    await expect(page.locator('.map-detail [data-order]')).toHaveCount(1);
    await page.locator('[name="from"]').fill('2000-01-01'); await page.locator('[name="to"]').fill('2000-01-02');
    await page.getByRole('button',{name:'Aplicar fechas',exact:true}).click();
    await expect(page.locator('.map-status')).toHaveText('No hay pedidos pagados en este período');
    expect(await page.locator('.map-graphic [data-region]').evaluateAll(nodes=>nodes.every(n=>n.style.fill==='rgb(68, 68, 77)'))).toBe(true);
    await recordGeometry(page,'desktop-empty');
    await page.locator('.map-graphic [data-region="05"]').focus(); await page.keyboard.press('Enter');
    await expect(page.locator('.map-detail')).toContainText('No hay pedidos pagados');
    await expect(page.locator('.map-tooltip')).toContainText('Canarias');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(out,'desktop-empty.png')});
    await page.screenshot({path:path.join(out,'empty.png'),fullPage:true});
    await page.route('**/api/admin/map?**',route=>route.fulfill({status:500,body:'private error'}));
    await page.locator('[name="preset"]').selectOption('month');
    await expect(page.locator('[data-retry]')).toBeVisible();
    await expect(page.locator('.map-status')).not.toContainText('private');
    await recordGeometry(page,'desktop-error');
    await expect(page.locator('.map-legend')).toContainText('Ventas no disponibles');
    await expect(page.locator('.map-status')).not.toContainText('No hay pedidos');
    await page.locator('.map-graphic [data-region="19"]').focus();
    await expect(page.locator('.map-tooltip')).toContainText('Melilla');
    await expect(page.locator('.map-tooltip')).toContainText('Ventas no disponibles');
    await page.evaluate(()=>window.scrollTo(0,0));
    await page.screenshot({path:path.join(out,'desktop-error.png')});
    await page.screenshot({path:path.join(out,'error.png')});
    await page.unroute('**/api/admin/map?**'); await page.locator('[data-retry]').click();
    await expect(page.locator('.map-status')).toBeEmpty();
    await page.reload(); await expect(page.locator('.map-graphic svg')).toBeVisible();
    const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
    await mobile.route('**/*',route=>new URL(route.request().url()).hostname==='127.0.0.1'?route.continue():route.abort());
    const phone=await mobile.newPage(); phone.on('pageerror',e=>errors.push(e.message));
    await phone.goto('http://127.0.0.1:43128/admin.html#section-map');
    await expect(phone.locator('.map-graphic svg')).toBeVisible();
    await phone.getByRole('switch',{name:'Modo oscuro'}).tap();
    await phone.locator('#sidebarToggle').tap(); await expect(phone.locator('#adminSidebar')).toBeVisible();
    await expect(phone.locator('nav > .sidebar-destination[data-nav-target="section-map"]')).toBeVisible();
    await expect(phone.locator('nav > .sidebar-destination[data-nav-target="section-map"]')).toBeInViewport();
    await expect.poll(async()=>Math.abs((await phone.locator('#adminSidebar').boundingBox()).x)<1).toBe(true);
    await expect(phone.locator('[aria-controls="navCliente"]')).toHaveAttribute('aria-expanded','false');
    await phone.screenshot({path:path.join(out,'mobile-menu.png')});
    await phone.locator('[data-nav-target="section-map"]').tap();
    const ceuta=phone.locator('.map-graphic [data-region="18"]');
    await ceuta.tap(); await expect(phone.locator('.map-tooltip')).toContainText('Ceuta');
    await expect(phone.locator('.map-detail')).toContainText('Ceuta');
    expect(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
    await phone.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
    await phone.evaluate(()=>window.scrollTo(0,0));
    await phone.screenshot({path:path.join(out,'mobile-map.png')});
    await recordGeometry(phone,'mobile-simulated');
    await phone.locator('.map-cartography').screenshot({path:path.join(out,'mobile-simulated.png')});
    await phone.goto('http://127.0.0.1:43128/admin.html#section-map?from=2000-01-01&to=2000-01-02&preset=custom');
    await expect(phone.locator('.map-status')).toHaveText('No hay pedidos pagados en este período');
    await recordGeometry(phone,'mobile-empty');
    expect(await phone.locator('.map-graphic [data-region]').evaluateAll(nodes=>nodes.every(n=>n.style.fill==='rgb(68, 68, 77)'))).toBe(true);
    await phone.locator('.map-graphic [data-region="19"]').tap();
    await expect(phone.locator('.map-tooltip')).toContainText('Melilla');
    await expect(phone.locator('.map-detail')).toContainText('No hay pedidos pagados');
    await phone.locator('.map-cartography').screenshot({path:path.join(out,'mobile-empty.png')});
    await phone.route('**/api/admin/map?**',route=>route.fulfill({status:500,body:'simulated failure'}));
    await phone.locator('[name="preset"]').selectOption('month');
    await expect(phone.locator('[data-retry]')).toBeVisible();
    await recordGeometry(phone,'mobile-error');
    await phone.locator('.map-graphic [data-region="18"]').tap();
    await expect(phone.locator('.map-tooltip')).toContainText('Ceuta');
    await expect(phone.locator('.map-tooltip')).toContainText('Ventas no disponibles');
    await phone.locator('.map-cartography').screenshot({path:path.join(out,'mobile-error.png')});
    await phone.unroute('**/api/admin/map?**');await phone.locator('[data-retry]').tap();
    await expect(phone.locator('.map-status')).toBeEmpty();
    expect(errors).toEqual([]); expect(mutations).toEqual([]); expect(dialogs).toEqual([]);
    expect(resources.every(r=>r.status===200&&r.type.includes('image/svg+xml'))).toBe(true);
    await fs.writeFile(path.join(out,'report.json'),JSON.stringify({errors,mutations,blockedExternal:external,resources,geometry,checks:'Independent main navigation; 19 visible regions while loading, empty and on error; default month/orders; hover/keyboard/touch; modal; pagination; presets/custom; sorting; EUR legend; empty/error/retry; mobile navigation and no overflow'},null,2));
    console.log('PASS: Mapa desktop/mobile review, local simulated data, no mutations.');
  } finally { await browser.close(); await new Promise(resolve=>server.close(resolve)); }
})().catch(e=>{console.error(e);process.exitCode=1;});
