// Generated by last-units-fixtures.cjs. Local disposable products only.
async page => {
  const fixture = __FIXTURE__, origin = 'http://127.0.0.1:3000';
  const assert = (ok, message) => { if (!ok) throw Error(message); };
  assert(new URL(page.url()).origin === origin, 'Local browser only');
  const item = label => fixture.products.find(p => p.label === label);
  const target = item('three-out');
  const writes = [];
  const observe = request => { if (/\/api\/(cart\/items|waitlist)/.test(request.url()) && request.method() !== 'GET') writes.push(request.url()); };
  page.on('request', observe);
  const store = async () => {
    await page.goto(origin + '/?search=' + fixture.tag + '#store');
    await page.waitForFunction(count => document.querySelectorAll('#productsGrid .product-card').length === count, fixture.products.length);
    await page.waitForFunction(() => !document.getElementById('preloader') || getComputedStyle(document.getElementById('preloader')).opacity === '0');
  };
  const open = async label => {
    await page.locator('.product-card[data-slug="' + item(label).slug + '"] .fav-add').click();
    await page.waitForFunction(() => document.getElementById('quickAdd').getAttribute('aria-hidden') === 'false');
  };
  const choose = size => page.locator('#qaSizes [data-size="' + size + '"]').click();
  const controls = async (status, fullyOut = false, allAvailable = false) => {
    assert(await page.locator('#qaAdd').isDisabled() === (status !== 'available'), 'Add state: ' + status);
    assert(await page.locator('#qaAdd').isVisible() === !fullyOut, 'Add visibility: ' + status);
    assert(await page.locator('#qaNotify').isDisabled() === (status !== 'out'), 'Alert state: ' + status);
    assert(await page.locator('#qaNotify').isVisible() === !allAvailable, 'Alert visibility: ' + status);
    assert(await page.locator('#qaDelivery').evaluate(el => el.classList.contains('qa-delivery--corner')), 'Delivery position class: ' + status);
    assert(await page.locator('#qaDelivery').evaluate(el => el.hidden) === (status !== 'available'), 'Delivery state: ' + status);
  };
  const noAction = async id => {
    const button = page.locator('#' + id), before = writes.length, url = page.url();
    assert(await button.isDisabled(), 'Native disabled required');
    const box = await button.boundingBox();
    await page.mouse.click(box.x + box.width / 2, box.y + box.height / 2);
    await button.evaluate(el => { el.click(); el.dispatchEvent(new MouseEvent('click', { bubbles: true })); el.focus(); });
    assert(await button.evaluate(el => document.activeElement !== el), 'Disabled button acquired focus');
    await page.keyboard.press('Enter'); await page.keyboard.press('Space');
    if (page.viewportSize().width < 640) {
      const cdp = await page.context().newCDPSession(page);
      await cdp.send('Emulation.setTouchEmulationEnabled', { enabled: true });
      await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: box.x + box.width / 2, y: box.y + box.height / 2 }] });
      await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] }); await cdp.detach();
    }
    assert(writes.length === before && page.url() === url, 'Disabled button performed an action');
  };
  const layout = async requireRow => {
    const result = await page.locator('.qa-footer').evaluate(footer => {
      const a = footer.querySelector('#qaLink').getBoundingClientRect(), b = footer.querySelector('#qaDelivery').getBoundingClientRect();
      const intersects = a.left < b.right && a.right > b.left && a.top < b.bottom && a.bottom > b.top;
      const right = footer.querySelector('#qaDelivery > span:last-child').getBoundingClientRect();
      const bounds = footer.getBoundingClientRect();
      return { centerDifference: Math.abs((a.top + a.bottom - b.top - b.bottom) / 2), intersects,
        leftGap: a.left - bounds.left, rightGap: bounds.right - right.right,
        overflow: footer.scrollWidth > footer.clientWidth + 1, display: getComputedStyle(footer).display };
    });
    assert(result.display === 'flex' && !result.intersects && !result.overflow, 'Footer overlap/overflow: ' + JSON.stringify(result));
    if (requireRow) assert(result.centerDifference <= 1, 'Footer vertical alignment: ' + JSON.stringify(result));
    assert(Math.abs(result.leftGap) <= 1 && Math.abs(result.rightGap) <= 1, 'Footer contents are not at the sides: ' + JSON.stringify(result));
    return result;
  };
  const geometry = [];
  for (const [surface, width, height] of [['desktop', 1365, 900], ['mobile', 390, 844], ['narrow', 320, 700]]) {
    await page.setViewportSize({ width, height }); await store();
    for (const size of ['M', 'S', 'L', 'XS', 'XL', 'XXL']) {
      await open('priority-' + size.toLowerCase());
      assert(await page.locator('#qaSizes [data-size="' + size + '"]').getAttribute('aria-checked') === 'true', surface + ' priority: ' + size);
      assert((await page.locator('#qaSizes [data-size]').evaluateAll(nodes => nodes.map(el => el.dataset.size))).join(',') === 'XS,S,M,L,XL,XXL', surface + ' visual order changed');
      await controls('available', false, size === 'M');
      if (size === 'M') {
        const vertical = await page.locator('#qaDelivery').evaluate(el => {
          const add = document.getElementById('qaAdd').getBoundingClientRect(), date = el.getBoundingClientRect();
          return { parent: el.parentElement.className, afterButton: date.top >= add.bottom,
            hiddenAlertHeight: document.getElementById('qaNotify').getBoundingClientRect().height,
            overflow: document.querySelector('.qa-panel').scrollWidth > document.querySelector('.qa-panel').clientWidth };
        });
        assert(vertical.parent === 'qa-footer' && vertical.afterButton && vertical.hiddenAlertHeight === 0 && !vertical.overflow, 'All-available delivery placement: ' + JSON.stringify(vertical));
        geometry.push({ surface, allAvailable: await layout(true) });
      }
      if (size === 'M') await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-all-available.png' });
      await page.locator('.qa-close').click();
    }
    await open('ring');
    const ringChoice = await page.locator('#qaSizes [aria-checked="true"]').getAttribute('data-size');
    assert(['US_7', 'US_8'].includes(ringChoice), 'Ring initial size is unavailable');
    await page.waitForFunction(() => [...document.querySelectorAll('.qa-media img')].every(img => img.complete));
    await page.evaluate(() => window.CRONOX_reloadCatalog());
    assert(await page.locator('#qaSizes [aria-checked="true"]').getAttribute('data-size') === ringChoice, 'Ring selection changed on update');
    await choose('US_6'); await controls('out');
    await page.evaluate(() => window.CRONOX_reloadCatalog());
    assert(await page.locator('#qaSizes [data-size="US_6"]').getAttribute('aria-checked') === 'true', 'Ring manual selection lost');
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-ring.png' });
    await page.locator('.qa-close').click(); await open('ring-empty');
    assert(await page.locator('#qaSizes [aria-checked="true"]').count() === 1, 'Exhausted ring has no initial size');
    await controls('out', true); await page.locator('.qa-close').click();
    await open('three-out');
    assert(await page.locator('#qaSizes [data-size="L"]').getAttribute('aria-checked') === 'true', 'Initial apparel choice leaked from another product');
    await controls('available'); await noAction('qaNotify');
    assert(await page.locator('#qaAdd').evaluate(el => getComputedStyle(el).backgroundColor) === 'rgb(255, 255, 255)', 'Available add is not white');
    geometry.push({ surface, normal: await layout(true) });
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-available.png' });
    await page.locator('#qaLink').evaluate(el => { el.textContent = 'Ver detalles del producto y toda la información sobre materiales, tallas y disponibilidad'; });
    await page.locator('#qaDelivery > span:last-child').evaluate(el => { el.prepend(document.createTextNode('Previsión orientativa del pedido completo: ')); });
    geometry.push({ surface, long: await layout(true) });
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-long-footer.png' });
    if (surface === 'mobile') {
      await page.setViewportSize({ width: 320, height: 700 });
      geometry.push({ surface: 'narrow', long: await layout(true) });
      await page.screenshot({ path: 'output/playwright/quick-add-selection/narrow-long-footer.png' });
      await page.setViewportSize({ width, height });
    }
    await choose('XS'); await controls('out'); await noAction('qaAdd');
    await page.locator('#qaSizes [data-size="XS"]').press('ArrowRight');
    assert(await page.locator('#qaSizes [data-size="S"]').getAttribute('aria-checked') === 'true', 'Keyboard cannot choose exhausted size');
    await controls('out');
    for (const size of ['L', 'XS', 'XL', 'M', 'L', 'S']) { await choose(size); await controls(['L', 'XL'].includes(size) ? 'available' : 'out'); }
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-selected-out.png' });
    const expected = target.variants.find(v => v.size === 'S');
    await page.locator('#qaNotify').click();
    await page.waitForURL(url => url.pathname === '/producto/' + target.slug && url.searchParams.get('waitlist') === String(expected.id) && url.searchParams.get('size') === 'S');
    await page.locator('#restockSize').waitFor();
    assert(await page.locator('#restockSize').inputValue() === String(expected.id), 'Selected alert product/size changed');
    assert(writes.length === 0, 'Navigation subscribed automatically');
    await store(); await open('empty'); await controls('out', true);
    assert(await page.locator('#qaSizes [data-size="M"]').getAttribute('aria-checked') === 'true', 'Fully exhausted initial priority');
    assert(await page.locator('#qaAdd').evaluate(el => el.getBoundingClientRect().height) === 0, 'Hidden purchase reserves space');
    assert(await page.locator('#qaDelivery').evaluate(el => el.getBoundingClientRect().height) === 0, 'Hidden delivery reserves space');
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-fully-out.png' });
    await page.locator('#qaNotify').click(); await page.locator('#restockSize').waitFor();
    assert(await page.locator('#restockSize').inputValue() === String(item('empty').variants.find(v => v.size === 'M').id), 'Fully exhausted initial selection changed');
    await page.waitForFunction(() => document.querySelector('[data-product-delivery]').hidden);
    assert(await page.locator('[data-product-delivery]').evaluate(el => el.getBoundingClientRect().height) === 0, 'PDP hidden delivery reserves space');
    await page.screenshot({ path: 'output/playwright/quick-add-selection/' + surface + '-pdp-out.png' });
  }
  await page.setViewportSize({ width: 1365, height: 900 }); await store(); await open('three-out'); await choose('L');
  const stock = async available => page.evaluate(async ({ id, variants, available }) => window.CRONOX_API.admin.updateAdminProduct(id,
    { variants: variants.map(v => ({ size: v.size, stockQty: available ? v.stockQty : 0 })) }), { id: target.id, variants: target.variants, available });
  let release, captured;
  const capturedPromise = new Promise(resolve => { captured = resolve; });
  const gate = new Promise(resolve => { release = resolve; });
  let first = true;
  const routeHandler = async route => {
    const hold = first; first = false;
    const response = await route.fetch();
    if (hold) { captured(); await gate; }
    await route.fulfill({ response });
  };
  await page.route('**/api/products/' + target.slug, routeHandler);
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await capturedPromise;
  await controls('unknown');
  await stock(false);
  await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.waitForFunction(() => !document.getElementById('qaNotify').disabled);
  assert(await page.locator('#qaSizes [data-size="L"]').getAttribute('aria-checked') === 'true', 'Stock refresh lost selection');
  await controls('out', true); release();
  await page.waitForFunction(() => performance.getEntriesByType('resource').filter(e => e.name.includes('/api/products/') && e.name.includes('three-out')).length >= 2);
  await controls('out', true); await page.unroute('**/api/products/' + target.slug, routeHandler);
  await stock(true); await page.evaluate(() => window.CRONOX_reloadCatalog());
  await controls('available');
  assert(await page.locator('#qaSizes [data-size="L"]').getAttribute('aria-checked') === 'true', 'Catalog refresh lost selection');
  await page.evaluate(async ({ id, variants }) => window.CRONOX_API.admin.updateAdminProduct(id,
    { variants: variants.map(v => ({ size: v.size, stockQty: 1 })) }), { id: target.id, variants: target.variants });
  await page.evaluate(() => window.CRONOX_reloadCatalog()); await controls('available', false, true);
  assert(await page.locator('#qaSizes [data-size="L"]').getAttribute('aria-checked') === 'true', 'Full availability refresh lost manual choice');
  assert(await page.locator('#qaDelivery').evaluate(el => el.parentElement.classList.contains('qa-footer')), 'Full availability lost the footer position');
  assert(await page.locator('#qaNotify').evaluate(el => el.getBoundingClientRect().height) === 0, 'Updated hidden alert reserves space');
  await stock(true); await page.evaluate(() => window.CRONOX_reloadCatalog()); await controls('available');
  let reopenRelease, reopenCaptured;
  const reopenGate = new Promise(resolve => { reopenRelease = resolve; });
  const reopenReady = new Promise(resolve => { reopenCaptured = resolve; });
  const reopeningHandler = async route => {
    const response = await route.fetch(); reopenCaptured(); await reopenGate;
    await route.fulfill({ response });
  };
  await page.route('**/api/products/' + target.slug, reopeningHandler);
  await page.evaluate(() => window.dispatchEvent(new Event('focus'))); await reopenReady;
  await page.locator('.qa-close').click(); await open('empty'); await choose('S');
  reopenRelease();
  await page.waitForFunction(() => performance.getEntriesByType('resource').filter(e => e.name.includes('/api/products/') && e.name.includes('three-out')).length >= 3);
  await controls('out', true);
  assert(await page.locator('#qaName').textContent() === fixture.tag + ' empty', 'Late response overwrote the reopened product');
  await page.unroute('**/api/products/' + target.slug, reopeningHandler);
  await page.locator('.qa-close').click();
  await page.goto(origin + '/producto/' + target.slug);
  await page.waitForFunction(() => !document.querySelector('[data-product-delivery]').hidden);
  await stock(false); await page.evaluate(() => window.dispatchEvent(new Event('focus')));
  await page.waitForFunction(() => document.getElementById('pAdd').disabled && document.querySelector('[data-product-delivery]').hidden);
  await page.evaluate(() => window.CRONOX_DELIVERY.refresh());
  assert(await page.locator('[data-product-delivery]').evaluate(el => el.hidden), 'PDP refresh resurrected delivery');
  await stock(true);
  page.off('request', observe);
  return { desktop: 'passed', mobile: 'passed', nativeDisabledMouseKeyboardTouch: 'passed', explicitProductAndSize: 'passed', noAutomaticSubscription: true,
    selectedSizePreservedOnStockChange: true, oldResponseIgnored: true, lateResponseAfterReopenIgnored: true, zeroStockDeliveryHidden: true, footerGeometry: geometry };
}
