ALTER TABLE "NewsletterSettings"
ADD COLUMN "desktopAsciiX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "desktopAsciiY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "desktopAsciiScale" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "mobileAsciiX" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "mobileAsciiY" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN "mobileAsciiScale" DOUBLE PRECISION NOT NULL DEFAULT 1;

CREATE TABLE "FooterPageContent" (
    "slug" TEXT NOT NULL,
    "html" TEXT NOT NULL,
    "revision" INTEGER NOT NULL DEFAULT 0,
    "updatedBy" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "FooterPageContent_pkey" PRIMARY KEY ("slug")
);

ALTER TABLE "FooterPageContent" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "FooterPageContent" FROM anon, authenticated;
