export const INVENTORY_LOW_STOCK_THRESHOLD = 5;
export const INVENTORY_MAX_STOCK = 2_147_483_647;
export const INVENTORY_AUDIT_ACTION = 'INVENTORY_STOCK_UPDATED';
export const INVENTORY_AUDIT_TARGET = 'PRODUCT_VARIANT';
export const INVENTORY_MANUAL_REASON = 'inventory_manual';
